import playersProvider from '.';

describe('playersProvider', () => {
  describe('getFootballPlayers', () => {
    it('should return for page 1 and pageSize 5 and sorted by Yds asc', async () => {
      expect(
        await playersProvider.getFootballPlayers({
          orderBy: 'Yds',
          orderDirection: 'asc',
          page: 1,
          pageSize: 3,
        }),
      ).toEqual({
        count: 326,
        data: [
          {
            Player: 'Sam Koch',
            Team: 'BAL',
            Pos: 'P',
            Att: 2,
            'Att/G': 0.1,
            Yds: -23,
            Avg: -11.5,
            'Yds/G': -1.4,
            TD: 0,
            Lng: 0,
            '1st': 0,
            '1st%': 0,
            '20+': 0,
            '40+': 0,
            FUM: 0,
          },
          {
            Player: 'DeMarcus Ayers',
            Team: 'PIT',
            Pos: 'WR',
            Att: 2,
            'Att/G': 1,
            Yds: -12,
            Avg: -6,
            'Yds/G': -6,
            TD: 0,
            Lng: 0,
            '1st': 0,
            '1st%': 0,
            '20+': 0,
            '40+': 0,
            FUM: 0,
          },
          {
            Player: 'Eli Manning',
            Team: 'NYG',
            Pos: 'QB',
            Att: 21,
            'Att/G': 1.3,
            Yds: -9,
            Avg: -0.4,
            'Yds/G': -0.6,
            TD: 0,
            Lng: 6,
            '1st': 2,
            '1st%': 9.5,
            '20+': 0,
            '40+': 0,
            FUM: 0,
          },
        ],
        page: 1,
        pageSize: 3,
      });
    });

    it('should return for page 1 and pageSize 5 and sorted by Lng asc', async () => {
      expect(
        await playersProvider.getFootballPlayers({
          orderBy: 'Lng',
          orderDirection: 'asc',
          page: 1,
          pageSize: 3,
        }),
      ).toEqual({
        count: 326,
        data: [
          {
            Player: 'Taiwan Jones',
            Team: 'OAK',
            Pos: 'RB',
            Att: 1,
            'Att/G': 0.1,
            Yds: -8,
            Avg: -8,
            'Yds/G': -0.6,
            TD: 0,
            Lng: -8,
            '1st': 0,
            '1st%': 0,
            '20+': 0,
            '40+': 0,
            FUM: 0,
          },
          {
            Player: 'Travis Kelce',
            Team: 'KC',
            Pos: 'TE',
            Att: 1,
            'Att/G': 0.1,
            Yds: -5,
            Avg: -5,
            'Yds/G': -0.3,
            TD: 0,
            Lng: -5,
            '1st': 0,
            '1st%': 0,
            '20+': 0,
            '40+': 0,
            FUM: 0,
          },
          {
            Player: 'Will Fuller',
            Team: 'HOU',
            Pos: 'WR',
            Att: 1,
            'Att/G': 0.1,
            Yds: -3,
            Avg: -3,
            'Yds/G': -0.2,
            TD: 0,
            Lng: -3,
            '1st': 0,
            '1st%': 0,
            '20+': 0,
            '40+': 0,
            FUM: 0,
          },
        ],
        page: 1,
        pageSize: 3,
      });
    });

    it('should return for page 1 and pageSize 5, sorted by Yds asc and a filter', async () => {
      expect(
        await playersProvider.getFootballPlayers({
          filter: { field: 'Player', value: 'sam' },
          orderBy: 'Yds',
          orderDirection: 'asc',
          page: 1,
          pageSize: 3,
        }),
      ).toEqual({
        count: 3,
        data: [
          {
            '1st': 0,
            '1st%': 0,
            '20+': 0,
            '40+': 0,
            Att: 2,
            'Att/G': 0.1,
            Avg: -11.5,
            FUM: 0,
            Lng: 0,
            Player: 'Sam Koch',
            Pos: 'P',
            TD: 0,
            Team: 'BAL',
            Yds: -23,
            'Yds/G': -1.4,
          },
          {
            '1st': 1,
            '1st%': 25,
            '20+': 0,
            '40+': 0,
            Att: 4,
            'Att/G': 0.3,
            Avg: 3.5,
            FUM: 0,
            Lng: '15',
            Player: 'Sammie Coates',
            Pos: 'WR',
            TD: 0,
            Team: 'PIT',
            Yds: 14,
            'Yds/G': 1,
          },
          {
            '1st': 3,
            '1st%': 15,
            '20+': 1,
            '40+': 0,
            Att: 20,
            'Att/G': 1.3,
            Avg: 2.7,
            FUM: 1,
            Lng: '24',
            Player: 'Sam Bradford',
            Pos: 'QB',
            TD: 0,
            Team: 'MIN',
            Yds: 53,
            'Yds/G': 3.5,
          },
        ],
        page: 1,
        pageSize: 3,
      });
    });
  });
});
